apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apache-config-job-role
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations: {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs: ["get", "list"]
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs: ["create"]
