{{- $secret := lookup "v1" "Secret" .Values.permissionMgrConfigs.metadata_namespace  "eric-enm-permissions-mgr-filestore-secret" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-enm-permissions-mgr.name" . }}-filestore-secret
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
  {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
type: Opaque
stringData:
      pom.yaml: |
         project:
            properties:
                  jboss_username: {{ .Values.permissionMgrConfigs.properties_jboss_username| default "305" | quote  }}
                  jboss_groupname: {{ .Values.permissionMgrConfigs.properties_jboss_groupname| default "206" | quote  }}
            url: {{ .Values.permissionMgrConfigs.properties_url| default "http://www.ericsson.com" | quote  }}
            organization:
                  name: {{ .Values.permissionMgrConfigs.properties_name| default "Ericsson" | quote  }}
            fsmaps:
                  fsmap:
                  -
                        mapping:
                        -
                              directory: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_directory| default "/ericsson/config_mgt" | quote  }}
                              dirmode: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_dirmode| default "550" | quote  }}
                              filemode: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_filemode| default "550" | quote  }}
                              uid: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_uid| default "0" | quote  }}
                              gid: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_gid| default "207" | quote  }}
                              directory_included: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_directory_included| default "true" | quote  }}
                              recurse_directories: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_recurse_directories| default "true" | quote  }}
                              dependency:
                                    includes:
                                          include: {{ .Values.permissionMgrConfigs.ericsson_config_mgt_include| default "test.txt" | quote  }}
            profiles:
                  profile:
                        id: {{ .Values.permissionMgrConfigs.id_id| default "fsmap_test" | quote  }}
                        nfsparameters:
                              complete_run: {{ .Values.permissionMgrConfigs.nfsparameters_complete_run| default "False" | quote  }}
                              run_as_non_root: {{ .Values.permissionMgrConfigs.nfsparameters_run_as_non_root| default "False" | quote  }}
                              sticky_bit: {{ .Values.permissionMgrConfigs.nfsparameters_sticky_bit| default "False" | quote  }}
                              setgid_bit: {{ .Values.permissionMgrConfigs.nfsparameters_setgid_bit| default "True" | quote  }}
                              setuid_bit: {{ .Values.permissionMgrConfigs.nfsparameters_setuid_bit| default "False" | quote  }}
                              g_u_bit: {{ .Values.permissionMgrConfigs.nfsparameters_g_u_bit| default "True" | quote  }}
                              ignore_user: {{ .Values.permissionMgrConfigs.nfsparameters_ignore_user| default "False" | quote  }}
                              default_dirmode: {{ .Values.permissionMgrConfigs.nfsparameters_default_dirmode| default "2777" | quote  }}
                              default_filemode: {{ .Values.permissionMgrConfigs.nfsparameters_default_filemode| default "7777" | quote  }}
                              default_username: {{ .Values.permissionMgrConfigs.nfsparameters_default_username| default "306" | quote  }}
                              default_groupname: {{ .Values.permissionMgrConfigs.nfsparameters_default_groupname| default "207" | quote  }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "eric-enm-permissions-mgr.name" . }}-filestore-secret
    labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
    annotations:
      "helm.sh/hook": pre-install,pre-upgrade
      "helm.sh/hook-weight": "-6"
    {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
type: Opaque
data: 
      {{- range $key, $value := $secret.data}}
      {{ $key }}: {{ $value | quote }}
      {{- end}}
{{- end }}