apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-enm-permissions-mgr.name" . }}-rolebinding
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
   {{- $securityPolicy := include "eric-enm-permissions-mgr.securityPolicy.annotations" . | fromYaml -}}
   {{- $default := include "eric-enm-permissions-mgr.annotations" . | fromYaml -}}
   {{- include "eric-enm-permissions-mgr.mergeAnnotations" (dict "location" .Template.Name "sources" (list $securityPolicy $default)) | trim | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-enm-permissions-mgr.name" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eric-enm-permissions-mgr.name" . }}-role
  apiGroup: rbac.authorization.k8s.io