apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-enm-permissions-mgr.name" . }}-role
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - pods
      - jobs
    verbs: ["get", "list", "create", "delete"]
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]
