apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-enm-permissions-mgr.name" . }}-task-secret
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
  {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
type: Opaque
data:
  client.key: dGVzdDI=
  client.crt: dGVzdA==