apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-enm-permissions-mgr.name" . }}-serviceaccount
  labels: {{- include "eric-enm-permissions-mgr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- include "eric-enm-permissions-mgr.annotations" . | nindent 4 }}
